---
# playbooks/BIG-IP/Upgrades/ha/vars/upgrade_vars.yml

# bigip_target_version: "17.1.1"
# bigip_image_filename: "BIGIP-17.1.1-0.0.4.iso"

bigip_install_volume: "HD1.2"
bigip_upgrade_dry_run: false

# Set true to fail back to original active after upgrade completes
bigip_failback: false

snapshot_output_dir: "{{ playbook_dir }}/../../../../snapshots"
